[env]
TERM = "alacritty"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font]
size = 12

[cursor.style]
shape = "Beam"

[window]
# decorations = "None"
dynamic_title = true
dynamic_padding = true
title = "Alacritty"
resize_increments = true
padding = { x = 1, y = 1 }
startup_mode = "Maximized"

[selection]
save_to_clipboard=true

# Colors (Gruvbox dark)
# https://github.com/alacritty/alacritty-theme/blob/master/themes/gruvbox_dark.toml
# credit goes to the original author https://github.com/morhetz

# Default colors
[colors.primary]
# # hard contrast background = = '#1d2021'
# background = '#282828'
# soft contrast 
background = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
