[env]
TERM = "alacritty"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font]
size = 13

[cursor.style]
shape = "Beam"

[window]
decorations = "none"
dynamic_title = true
dynamic_padding = true
opacity = 0.7
blur = true
title = "Alacritty"
resize_increments = true
padding = { x = 1, y = 1 }
startup_mode = "Maximized"

[selection]
save_to_clipboard=true
