#!/usr/bin/env fish
# Check if yq is installed
if not command -v yq >/dev/null
    echo "error: yq is not installed. Please install yq to proceed."
    exit 1
end

# Define the directory where this script is located
set dir (dirname (realpath (status --current-filename)))
set -Ux DOTFILES $dir
set config_file "$DOTFILES/install.yaml"
echo "-> DOTFILES is set to $DOTFILES"

function execute_commands -a commands
    for command in $commands
        echo $command
    end

    for command in $commands
        set_color green
        echo "  | $command"
        set_color normal

        set_color red
        # fish -c "$command" 2>&1 | sed "s/^/  | /"
        set_color normal

        # if test $status -ne 0
        #     set_color red
        #     echo "Error executing previous command, continuing..."
        #     set_color normal
        # end
    end
end

# Read and execute the list of pre-commands listed in $DOTFILES/install.yaml
set pre_commands (yq eval '.pre_commands[]' $config_file)
echo "-> Executing pre-commands..."
execute_commands $pre_commands

# Create the symbolic links
set symlinks (yq eval '.symlinks[]' $config_file)
set symlinks_darwin (yq eval '.symlinks-darwin[]' $config_file)
set symlinks_linux (yq eval '.symlinks-linux[]' $config_file)

if uname -s | string match -r Darwin
    echo "  | ! Detected macOS, adding macOS symlinks"
    set symlinks $symlinks_darwin $symlinks
end

if uname -s | string match -r Linux
    echo "  | ! Detected Linux, adding Linux symlinks..."
    set symlinks $symlinks_linux $symlinks
end

echo "-> Creating symbolic links..."

function create_symlink -a source -a dest
    # Check if the symlink already exists
    if test -L $dest
        set_color yellow
        echo "  | ! Removing existing symlink: $dest"
        set_color normal
        rm $dest
    else if test -e $dest
        set_color yellow
        echo "  | ! Warning: $dest already exists and is not a symlink, backup"
        mv $dest $dest.backup
        echo "$dest -> $dest.backup"
        set_color normal
    end

    set_color red
    ln -sf $source $dest | sed "s/^/  |  /"
    if not test $status -ne 0
        set_color green
        echo "  | @ $dest -> $source"
        set_color normal
    end
end


for symlink in $symlinks
    set key_value (string split ":" $symlink)

    set source (string trim -c " " $key_value[1])
    set source (eval "echo $source")

    set dest (string trim -c " " $key_value[2])
    set dest (eval "echo $dest")

    create_symlink $dest $source
end

# Same but post
set post_commands (yq eval '.post_commands[]' $config_file)
# for command in $post_commands
#     echo $command
# end

echo "-> Executing post-commands..."
execute_commands $post_commands
