
[settings]
default_keys = false
animate = true
default_disable = false
focus_follows_mouse = false
mouse_follows_focus = false
mouse_hides_on_focus = false

outer_gap = 8
inner_gap = 4
default_layout_kind = "tree"
group_bars.enable = true
group_bars.thickness = 6
group_bars.horizontal_placement = "top"
group_bars.vertical_placement = "right"
status_icon.enable = true


[keys]
"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }
"Alt + Meta + H" = { move_node = "left" }
"Alt + Meta + J" = { move_node = "down" }
"Alt + Meta + K" = { move_node = "up" }
"Alt + Meta + L" = { move_node = "right" }
"Alt + Ctrl + H" = { resize = { direction = "left", percent = 5 } }
"Alt + Ctrl + J" = { resize = { direction = "down", percent = 5 } }
"Alt + Ctrl + K" = { resize = { direction = "up", percent = 5 } }
"Alt + Ctrl + L" = { resize = { direction = "right", percent = 5 } }
"Alt + Meta + Backslash" = { split = "horizontal" }
"Alt + Meta + Minus" = { split = "vertical" }
"Alt + Meta + Backslash" = { group = "horizontal" }
"Alt + Meta + Minus" = { group = "vertical" }
"Alt + Meta + U" = "ungroup"
"Alt + Meta + Ctrl + Space" = "toggle_window_floating"
"Alt + Shift + Space" = "toggle_focus_floating"
"Alt + Z" = "toggle_fullscreen"

[settings.experimental]
status_icon.space_index = true
status_icon.color = false
status_icon.enable = true
scroll.enable = false
