# # # - General

set -g default-terminal "xterm-256color"
set -s escape-time 1                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g @shell_mode 'vi'
set-option -g allow-passthrough on
# set -g destroy-unattached on
set-option -g detach-on-destroy off

# # --------- Binds

# - Set Prefix
unbind C-b
set -g prefix C-a

# - General
bind r source-file ~/.tmux.conf

# - Visual Mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # Begin selection in copy mode.

# - Windows
bind Space last-window # Switch to last window
bind t new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Kill session
bind X confirm-before "kill-session -t ''"

# Toggle claude
bind a run-shell "$DOTFILES/tmux/toggle-claude.fish '#{pane_current_path}'"
bind-key -n C-u if-shell -F '#{?@is_claude_pane,1,0}' 'copy-mode -u' 'send-keys C-u'
bind-key -n C-d if-shell -F '#{?@is_claude_pane,1,0}' 'copy-mode -u' 'send-keys C-d'

# - Lazygit
## bind g if-shell "ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '(n?vim?|n?vim_.+)$'" "send-keys Space g l" "popup -d '#{pane_current_path}' -xC -yC -w80% -h80% -E 'fish \"-c eval (ssh-agent -c) && lazygit\"'"
bind g if-shell "ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '(n?vim?|n?vim_.+)$'" "send-keys Space g l" "popup -d '#{pane_current_path}' -xC -yC -w80% -h80% -E 'fish \"-c lazygit\"'"
bind @ run-shell "tmux display-message -p '#{pane_current_command}: #{session_id}:#{window_id}:#{pane_id}'"

# # # - Theme
set -g status-left-length 85
set -g status-left ""
set -g window-status-current-format "#[fg=black,bold bg=default] │#[fg=white bg=black]#I: #W#[fg=black,bold bg=default]│"
set -g window-status-format "|#[fg=white bg=default]#I: #W|"
set -g status-style bg=default
set -g status-right "#{pane_current_command}: #{session_id}:#{window_id}:#{pane_id}:"
set -g status-justify centre

set-option -g set-titles on
set-option -g set-titles-string 'tmux'

# # # - Plugins

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Fingers
set -g @plugin 'Morantron/tmux-fingers'
set -g @fingers-key J
set -g @fingers-jump-key j
bind e run -b "#{@fingers-cli} start #{pane_id} --patterns path --main-action 'xargs tmux new-window nvim'"

# - Load tpm
set -g @plugin 'tmux-plugins/tpm'

# ----------- END
run '~/.tmux/plugins/tpm/tpm'
