# Options
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -s escape-time 1
set -sg repeat-time 600
set -s focus-events on
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g @shell_mode 'vi'
set-option -g allow-passthrough on
# set -g destroy-unattached on
set-option -g detach-on-destroy off
set -g status off

# Keys and Binds
unbind -a
