# Options

set -g default-terminal "xterm-256color"
set -s escape-time 1                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g @shell_mode 'vi'
set-option -g allow-passthrough on
# set -g destroy-unattached on
set-option -g detach-on-destroy off

# Keys and Binds

set-window-option -g mode-keys vi
unbind C-b
set -g prefix C-a

bind R source-file ~/.tmux.conf
bind -T copy-mode-vi 'v' send -X begin-selection # Begin selection in copy mode.
bind \; last-pane -Z
bind Space last-window # Switch to last window
bind t new-window -c "#{pane_current_path}"
bind / copy-mode \; send-key ?
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind X confirm-before "kill-session -t ''"
bind g if-shell "ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '(n?vim?|n?vim_.+)$'" "send-keys Space g l" "popup -d '#{pane_current_path}' -xC -yC -w80% -h80% -E 'fish \"-c lazygit\"'"
bind p run-shell "tmux display-popup -xC -yC -w80% -h80% -d '#{pane_current_path}' -E fish"
bind @ run-shell "(echo 'tmux pane: #{session_id}:#{window_id}:%#{pane_id}' | pbcopy) && tmux display-message 'Copied pane info to clipboard'"
# Claude
bind a run-shell "fish $DOTFILES/tmux/claude-sessions-run.fish #{pane_current_path} || true"
bind r run-shell "fish $DOTFILES/tmux/git-repos-run.fish || true"

# Theme
set -g status-left-length 85
set -g status-left ""
set -g window-status-current-format "#[fg=black,bold bg=default] │#[fg=white bg=black]#I: #W#[fg=black,bold bg=default]│"
set -g window-status-format "|#[fg=white bg=default]#I: #W|"
set -g status-style bg=default
set -g status-right "#{pane_current_command}: #{session_id}:#{window_id}:#{pane_id}:"
set -g status-justify centre

set-option -g set-titles on
set-option -g set-titles-string 'tmux'

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'schasse/tmux-jump'

# TPM
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
